//
// Created by huzongyao on 2018/6/21.
//

#ifndef PLATINUMMEDIA_CALLBACKTYPES_H
#define PLATINUMMEDIA_CALLBACKTYPES_H

const int CALLBACK_EVENT_ON_NEXT = 0x1001;
const int CALLBACK_EVENT_ON_PAUSE = 0x1002;
const int CALLBACK_EVENT_ON_PLAY = 0x1003;
const int CALLBACK_EVENT_ON_PREVIOUS = 0x1004;
const int CALLBACK_EVENT_ON_SEEK = 0x1005;
const int CALLBACK_EVENT_ON_STOP = 0x1006;
const int CALLBACK_EVENT_ON_SET_AV_TRANSPORT_URI = 0x1007;
const int CALLBACK_EVENT_ON_SET_PLAY_MODE= 0x1008;
const int CALLBACK_EVENT_ON_SET_VOLUME = 0x1009;
const int CALLBACK_EVENT_ON_SET_MUTE = 0x100A;

#endif //PLATINUMMEDIA_CALLBACKTYPES_H
