//
// Created by huzongyao on 2018/6/21.
//

#ifndef PLATINUMMEDIA_CALLBACKTYPES_H
#define PLATINUMMEDIA_CALLBACKTYPES_H

const int CALLBACK_EVENT_ON_NEXT = 1001;
const int CALLBACK_EVENT_ON_PAUSE = 1002;
const int CALLBACK_EVENT_ON_PLAY = 1003;
const int CALLBACK_EVENT_ON_PREVIOUS = 1004;
const int CALLBACK_EVENT_ON_SEEK = 1005;
const int CALLBACK_EVENT_ON_STOP = 1006;
const int CALLBACK_EVENT_ON_SET_AV_TRANSPORT_URI = 1007;
const int CALLBACK_EVENT_ON_SET_PLAY_MODE = 1008;
const int CALLBACK_EVENT_ON_SET_VOLUME = 1009;
const int CALLBACK_EVENT_ON_SET_MUTE = 1010;

#endif //PLATINUMMEDIA_CALLBACKTYPES_H
