/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plutinosoft_platinum_UPnP */

#ifndef _Included_com_plutinosoft_platinum_UPnP
#define _Included_com_plutinosoft_platinum_UPnP
#ifdef __cplusplus
extern "C" {
#endif

#define BRIDGE_FUNC(x) Java_com_plutinosoft_platinum_UPnP_ ## x

/*
 * Class:     com_plutinosoft_platinum_UPnP
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
BRIDGE_FUNC(_1init)(JNIEnv *, jclass);

/*
 * Class:     com_plutinosoft_platinum_UPnP
 * Method:    _start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
BRIDGE_FUNC(_1start)(JNIEnv *, jclass, jlong);

/*
 * Class:     com_plutinosoft_platinum_UPnP
 * Method:    _stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
BRIDGE_FUNC(_1stop)(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
